version: '3'

services:
   mysql:
     image: mysql:5.7.22
     container_name: mysql
     restart: always
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: Hqufnacp@246
       MYSQL_DATABASE: cloudts
       MYSQL_USER: udecideadmin
       MYSQL_PASSWORD: Hqufnacp@246
     ports:
       - "3306:3306"

   faveo:
     container_name: cloudts
     depends_on:
       - mysql
     image: 1thegingerninja1/cloudts
     links:
       - mysql:mysql
     ports:
       - "80:80"
       - "443:443"
     restart: always


volumes:
    db_data:
